services:
  - type: web
    name: blinkit-backend
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    healthCheckPath: /
    envVars:
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: blinkit-db
          property: connectionString
      - key: CORS_ORIGINS
        value: https://deveshpandi-0202.github.io,https://blinkit-backend-mg62.onrender.com
      - key: PYTHON_VERSION
        value: 3.11.9

  - type: postgres
    name: blinkit-db
    plan: free
    databaseName: blinkit
